applicaiton:
  name: passwordkeeper
  version: 1.0.0-SNAPSHOT

db:
  default:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pkdb
    user: pk
    password: pkpassword
    pool:
      size: 10

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
