applicaiton:
  name: passwordkeeper
  version: 1.0.0-SNAPSHOT

server:
  port: 11434

#spring:
#  datasource:
#    url: jdbc:h2:mem:training
#    #url: jdbc:h2:file:C:/data/training
#    driverClassName: org.h2.Driver
#    username: sa
#    password: pa
#  h2:
#    console:
#      enabled: true

#db:
#  default:
#    driver: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/pkdb
#    user: pk
#    password: pkpassword
#    pool:
#      size: 10

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/pkdb
    username: pk
    password: pkpassword
